In [1]:
import numpy as np
import time

# Set random seed for reproducibility
np.random.seed(42)
print("NumPy version:", np.__version__)

# Compare Loop vs. Vectorization Speed
prices = list(range(1, 1_000_001))
start = time.time()
discounted_loop = [p * 0.95 for p in prices]
loop_time = time.time() - start
print(f"Loop version: {loop_time:.4f} seconds")

prices_np = np.arange(1, 1_000_001)
start = time.time()
discounted_np = prices_np * 0.95
np_time = time.time() - start
print(f"NumPy version: {np_time:.4f} seconds")
print(f"NumPy was about {loop_time / np_time:.0f}x faster")

NumPy version: 2.4.6
Loop version: 0.0805 seconds
NumPy version: 0.0049 seconds
NumPy was about 17x faster


In [2]:
# Array creation methods
a = np.array([10, 20, 30, 40])
zeros = np.zeros((2, 3))
ones = np.ones((3, 3))
seq = np.arange(0, 10, 2)
lin = np.linspace(0, 1, 5)  # 5 evenly spaced points between 0 and 1

print("a:", a)
print("zeros:\n", zeros)
print("ones:\n", ones)
print("seq:", seq)
print("lin:", lin)

# Check array attributes
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nshape:", matrix.shape)  # (rows, columns)
print("ndim:", matrix.ndim)      # number of dimensions
print("size:", matrix.size)      # total number of elements
print("dtype:", matrix.dtype)    # data type

a: [10 20 30 40]
zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
ones:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
seq: [0 2 4 6 8]
lin: [0.   0.25 0.5  0.75 1.  ]

shape: (2, 3)
ndim: 2
size: 6
dtype: int64


In [3]:
# Reshaping and flattening
flat = np.arange(12)
reshaped = flat.reshape(3, 4)
back_to_flat = reshaped.flatten()

print("reshaped (3x4):\n", reshaped)

# Indexing, slicing, and filtering
sales = np.array([120, 85, 200, 0, 60, 300, 45])
print("\nfirst 3 sales:", sales[:3])
print("every other sale:", sales[::2])

# Boolean masking
mask = sales > 100
print("sales above 100:", sales[mask])
print("days with zero sales:", sales[sales == 0])

reshaped (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

first 3 sales: [120  85 200]
every other sale: [120 200  60  45]
sales above 100: [120 200 300]
days with zero sales: [0]


In [4]:
# Element-wise operations (no loops needed)
units_sold = np.array([10, 25, 8, 40])
unit_price = np.array([15000, 22000, 9500, 30000]) # KRW
revenue = units_sold * unit_price

print("revenue per product:", revenue)
print("total revenue:", revenue.sum())

# Broadcasting across 2D array (3 stores x 4 products)
store_sales = np.array([
    [100, 200, 150, 300],
    [120, 180, 170, 250],
    [90, 210, 160, 280]
])

# 10% discount stretched across all elements
print("after 10% discount:\n", store_sales * (1 - 0.10))

# Per-product bonus (shape (4,)) broadcast down rows
product_bonus = np.array([5, 0, 10, 2])
print("\nwith per-product bonus:\n", store_sales + product_bonus)

revenue per product: [ 150000  550000   76000 1200000]
total revenue: 1976000
after 10% discount:
 [[ 90. 180. 135. 270.]
 [108. 162. 153. 225.]
 [ 81. 189. 144. 252.]]

with per-product bonus:
 [[105 200 160 302]
 [125 180 180 252]
 [ 95 210 170 282]]


In [5]:
# Collapse along specific dimensions
print("total per store (axis=1):", store_sales.sum(axis=1))
print("total per product (axis=0):", store_sales.sum(axis=0))
print("overall mean:", store_sales.mean())
print("best-selling product index per store:", store_sales.argmax(axis=1))

total per store (axis=1): [750 720 740]
total per product (axis=0): [310 590 480 830]
overall mean: 184.16666666666666
best-selling product index per store: [3 3 3]


In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("A:\n", A)
print("A transposed:\n", A.T)
print("\nElement-wise multiply (A * B):\n", A * B)
print("\nMatrix multiply (A @ B):\n", A @ B) # Same as np.dot(A, B)

A:
 [[1 2]
 [3 4]]
A transposed:
 [[1 3]
 [2 4]]

Element-wise multiply (A * B):
 [[ 5 12]
 [21 32]]

Matrix multiply (A @ B):
 [[19 22]
 [43 50]]


In [7]:
# Rows: 3 portfolios | Columns: shares held in 4 assets
holdings = np.array([
    [10, 5, 0, 20],
    [0, 15, 10, 5],
    [8, 8, 8, 8]
])

# Share price for each of the 4 assets (KRW)
prices = np.array([50000, 120000, 75000, 30000])

# Compute total portfolio values in one step
portfolio_value = holdings @ prices
print("value of each portfolio (KRW):", portfolio_value)

value of each portfolio (KRW): [1700000 2700000 2200000]


In [8]:
# Identity matrix & inverse
I = np.eye(3)
M = np.array([[2, 1], [1, 3]])
M_inv = np.linalg.inv(M)

print("M @ M_inv (should be identity):\n", np.round(M @ M_inv, 2))

# Solve linear system: 2x + y = 5; x + 3y = 10
coeffs = np.array([[2, 1], [1, 3]])
results = np.array([5, 10])
solution = np.linalg.solve(coeffs, results)

print("\nsolution [x, y]:", solution)

M @ M_inv (should be identity):
 [[ 1.  0.]
 [-0.  1.]]

solution [x, y]: [1. 3.]


In [9]:
np.random.seed(42)

# Basic distributions
uniform_samples = np.random.rand(5)                  # Uniform [0, 1)
integers = np.random.randint(1, 7, size=10)           # 10 dice rolls
normal_samples = np.random.normal(loc=170, scale=8, size=5) # Heights in cm

print("uniform:", uniform_samples)
print("dice rolls:", integers)
print("normal samples:", normal_samples)

# Vectorized simulation: 100,000 dice rolls
rolls = np.random.randint(1, 7, size=100_000)
prob_six = (rolls == 6).mean()
avg_roll = rolls.mean()

print(f"\nP(rolling a 6): {prob_six:.4f} (theoretical: {1/6:.4f})")
print(f"average roll: {avg_roll:.3f} (theoretical: 3.5)")

uniform: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
dice rolls: [3 3 3 5 4 3 6 5 2 4]
normal samples: [170.17777461 166.57765669 165.74546072 169.06019599 171.77663121]

P(rolling a 6): 0.1663 (theoretical: 0.1667)
average roll: 3.503 (theoretical: 3.5)


In [10]:
np.random.seed(1)
days = 30
price = 10000 # Starting price in KRW

# ~0.1% avg daily return with 2% daily volatility
daily_returns = np.random.normal(loc=0.001, scale=0.02, size=days)

# Apply compounding across all 30 days without a loop
simulated_prices = price * np.cumprod(1 + daily_returns)

print("simulated daily prices:\n", np.round(simulated_prices, 0))
print(f"\nfinal price after {days} days: {round(simulated_prices[-1], 0)} KRW")

simulated daily prices:
 [10335. 10219. 10121.  9914. 10095.  9641.  9987.  9845.  9918.  9878.
 10177.  9768.  9714.  9649.  9878.  9671.  9647.  9487.  9505.  9625.
  9423.  9648.  9831.  9940. 10129. 10001.  9986.  9809.  9766.  9880.]

final price after 30 days: 9880.0 KRW
